# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Resume"
license = "MIT"
licenselink = "https://github.com/butlerx/resume-template/blob/master/LICENSE.md"
description = "A resume Template"
homepage = "https://cian.notthe.cloud"
tags = ["CV", "Resume"]
features = []
min_version = "0.20.7"

[author]
  name = "Cian Butler"
  homepage = "https://cian.notthe.cloud"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
